@host = http://localhost:5207

POST {{host}}/auth/register
Content-Type: application/json

{
  "firstName": "first name",
  "lastName": "last name",
  "email": "ddd@example.com",
  "password": "dd123456."
}