@host = http://localhost:5207

Get {{host}}/blog
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnaXZlbl9uYW1lIjoiRGF2aWQiLCJmYW1pbHlfbmFtZSI6IkdvZ2dpbnMiLCJqdGkiOiI1ODczMDRhNC02MWJlLTRjMDctYWFmZi01MWVjNGI4YzBlMDAiLCJzdWIiOiJjMWNjNjQ5ZS02NjZiLTQxZmEtYWMwMS1hY2NlYTU1Y2NkOGUiLCJleHAiOjE3MzUyNDY0MDksImlzcyI6IkJsb2ciLCJhdWQiOiJCbG9nIn0.QVQ1NCHNZuN5Xv6KhsPbp244hFbbdsW-PaxoFir9vaI